[build]
builder = "nixpacks"
buildCommand = "cd frontend && npm install && npm run build && cp -r dist ../backend/public && cd ../backend && npm install && npm run build"

[deploy]
startCommand = "cd backend/build && node bin/server.js"
healthcheckPath = "/api/health"
restartPolicyType = "on_failure"
