import { execSync } from 'node:child_process'
import { writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))

let version = 'unknown'
try {
  version = execSync('git rev-parse --short HEAD', { stdio: ['pipe', 'pipe', 'pipe'] })
    .toString()
    .trim()
} catch {
  version = `build-${Date.now()}`
}

const content = `// Auto-generated by scripts/set-version.mjs — do not edit\nexport const APP_VERSION = '${version}'\n`
writeFileSync(join(__dirname, '../app/version.ts'), content)
console.log(`[set-version] APP_VERSION = ${version}`)
